owl/owl

app/controllers/SearchController.php, app/database/migrations/2015_01_24_142354_create_tags_fts.php, app/libraries/FtsUtils.php, app/models/ItemFts.php, app/models/Tag.php, app/models/TagFts.php, app/views/search/index.blade.php
=> Feature tag search pr

app/controllers/SearchController.php, app/start/custom_macro.php, app/views/search/index.blade.php
=> usersearch

app/libraries/CustomMarkdown.php
added null for width & height to avoid exception
=> [BUGFIX] Exception occured when invliad image string is given

app/Http/Controllers/TagController.php, app/Http/routes.php, app/Repositories/Tag.php, app/Services/TagService.php, resources/views/layouts/navbar-menu.blade.php, resources/views/tags/index.blade.php
=> タグ一覧ページを作成する

public/css/style.css, public/js/contents.js, resources/views/layouts/items-show-sidebar.blade.php
自前で2時間かけてBootstrapで5分でできましたけどCSSのお勉強になって圧倒的成長✊につながったので全然微塵も全く本当に心の底から後悔はないです🙆
=> クリップボードボタンにツールチップを追加

public/js/preview.js
#27 
記事編集画面でのプレビュー時にhighlight.jsが効くようにしました。
レビューとマージをお願いします。
=> プレビュー時のハイライト修正

public/js/slide.js
=> owl downをescキーで抜けられるようにした

readme.md
`--seed` オプションが抜けてて `readme.md` のままでは動かなかったので追加しました。
=> readme.md のマイグレーションのところに `--seed` オプションを追加しました

public/css/print.css, resources/views/layouts/master.blade.php
for #32 
I just add 'display:none' for non content related blocks and elements.
=> Add media query for browser print

resources/views/comment/body.blade.php, resources/views/items/show.blade.php
#34 対応。ログインしてなくても記事のコメントを確認できるようにした。
=> #34 ログインしてなくてもコメントを確認できるようにした

public/css/style.css, public/js/slide.js
Issue #54 
owl downのスタイルシートに下記修正を加えました。
- スライドの長さが縦に収まらない時、スクロールできる
- 見えない記事のスクロールバーを非表示にする
レビューお願いします。
=> fix style for owl down

app/Services/SearchService.php
=> #84 fix: search pagination bug

app/Repositories/Fluent/StockRepository.php
=> #85 fix: favorite count bug

public/js/like.change.js, public/js/stock.change.js, resources/views/items/show.blade.php
Issue #86
挙動の原因としてはBootstrap製JSだったのですが、内部的にどう処理してるかちんぷんかんぷんだったので純jQueryの処理に置き換えました。
ついでに通信中の文言も変えました。
レビューをお願いします。
=> お気に入り/いいねボタンの挙動を修正

setup_app.sh
=> #92 modify: add permission setting

README.md
=> #59 prepare demo site

.env.example, README.md
=> #101 Prepare Documentaion

app/Http/Controllers/UserRoleController.php
=> #102 管理者初期設定( user/role/initial ) でエラーが発生している

resources/assets/stylus/style.styl
=> #95 modify p tag style after h1 tag

setup_app.sh, update_app.sh
=> #111 シェルでのマイグレーションが対話式になる

README.md, setup_app.sh, update_app.sh
refs. #112 
- mbstring
- pdo-sqlite
- openssl
=> #112 セットアップ／アップデート時のモジュールチェックを充実

update_app.sh
=> #122 don't overwrite .env file 

config/app.php, resources/views/items/create.blade.php, resources/views/layouts/contents-sidebar.blade.php, resources/views/layouts/items-show-sidebar.blade.php, resources/views/stocks/index.blade.php, resources/views/templates/index.blade.php, resources/views/user/show.blade.php, update_app.sh
=> [Release] 2.5.3

public/js/comment.create.js, public/js/item/edit.js, resources/views/comment/form.blade.php, resources/views/items/create.blade.php, resources/views/items/edit.blade.php
=> #94 Fix Image upload bug

public/js/image.upload.js
=> #46 fix image size validation

.editorconfig, .env.example, .eslintrc, CONTRIBUTE.md, README.md, composer.json, composer.lock
- contribute.md
- EditorConfig
- fixerでPSR2に対応するためにphpcs導入
- eslint
refs. #139
=> #139 improve develop environment

public/js/edit/switch.js, resources/assets/stylus/style.styl, resources/views/user/edit/_mail-notify.blade.php
=> #81 Fix Layout bug on mail notify settings

app/Services/AuthService.php
Issue #151 
ユーザリポジトリから直接カラムをアップデートするよう修正しました。
動作確認とマージをお願いします〜
=> パスワード再設定のバグ修正

resources/macros/custom_macro.php
macroメソッドでエスケープ処理が入ってなかったので入れたのと、ついでにリファクタリングを行いました。
データ挿入時にバリデーションかけてることは理解してるんですが、管理できない範囲になった時に脆弱性の温床になりうるので。。。
マージ検討お願いします。
=> HTMLファサードのmacroメソッドを修正

app/Handlers/Events/SlackNotification.php, tests/Handlers/SlackNotificationTest.php
=> 非公開/限定公開の記事作成、編集時はSlack通知を行わない

app/Http/Controllers/ItemController.php, resources/views/items/history.blade.php
=> 記事変更履歴に表示される記事タイトルの修正

resources/macros/custom_macro.php, resources/views/errors/503.blade.php, resources/views/layouts/master.blade.php
=> #165 SSL化に対応できるように微修正

README.md
Delete the demo site because it costs maintenance costs.
=> #171 Remove demo site
